dm-writeboost-target.c: Fix build error in 6.10
akiradeveloper/dm-writeboost pull request #259
Opened 2024-10-03 06:26 UTC by WestonReed

`bdev->bd_inode` was removed in 6.10; replace it with `bdev_nr_sectors`

See kernel commit: https://github.com/torvalds/linux/commit/203c1ce0bb063d1620698e39637b64f2d09c1368

Closes #256

2024-10-03 06:31 UTC, WestonReed commented on src/dm-writeboost-target.c
> +#endif
`bdev_nr_sectors` was [added in 5.11](https://elixir.bootlin.com/linux/v5.11-rc1/A/ident/bdev_nr_sectors), so we could switch this to build with 5.11+ kernels instead. I'm unsure what the best practice here is though.

2024-10-03 06:36 UTC, WestonReed commented on src/dm-writeboost-target.c
> +#endif
`bdev_nr_sectors` was [added in 5.11](https://elixir.bootlin.com/linux/v5.11-rc1/A/ident/bdev_nr_sectors), so we could switch this to build with 5.11+ kernels instead. I'm unsure what the best practice here is though.

2024-10-30 00:10 UTC, akiradeveloper requested changes

2024-10-30 00:10 UTC, akiradeveloper commented on src/dm-writeboost-target.c
> +#endif
@WestonReed Thank you for the PR.

Not sure this is the best practice in the community though, I think the switch boundary should be 5.11 to make the code more informative: your suggestion here seems to me that `bdev_nr_sectors` was introduced in 6.10.

2024-11-05 04:33 UTC, WestonReed commented
@akiradeveloper Makes sense - I've added another commit to use 5.11 as the switch instead.

2024-11-05 21:38 UTC, merged